import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ThemeRegistry from "../components/ThemeRegistry";
import { InitColorSchemeScript, Toolbar } from "@mui/material";
import AppBar from "@/components/AppBar";

export const metadata: Metadata = {
  title: "FlorianRth-Portfolio",
  description: "Generated by create next app",
};

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider>
          <ThemeRegistry>
            <AppBar />
            <Toolbar sx={{ position: "relative" }} />
            <InitColorSchemeScript attribute="class" />
            {children}
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
